name = "liver-scraper-main"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "e610573ff233746b39a509deadc4ee36"

[triggers]
crons = ["0 * * * *"]

[[kv_namespaces]]
binding = "LIVER_DATA"
id = "a9658ebf09ed49bba4ea6b35af67f9eb"

[[kv_namespaces]]
binding = "IMAGE_HASHES"
id = "faaeff9c9c194751bc1e20549fdb3161"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "liver-images"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "49596f0e6e73472aa48904f16a55ec46"

[[d1_databases]]
binding = "REVIEWS_DB"
database_name = "liver-reviews-db"
database_id = "d6629c6c-3a67-4538-beda-01d18b296af0"
