name = "liver-scraper-details"
main = "src/details-scraper.js"
compatibility_date = "2024-01-01"
account_id = "e610573ff233746b39a509deadc4ee36"

# Worker2: 詳細情報専門 - 毎時5分と35分に実行（Main Workerとの競合回避）
[triggers]
crons = ["5,35 * * * *"]

# 共有KVとR2バインディング
[[kv_namespaces]]
binding = "LIVER_DATA"
id = "a9658ebf09ed49bba4ea6b35af67f9eb"

[[kv_namespaces]]
binding = "IMAGE_HASHES"
id = "faaeff9c9c194751bc1e20549fdb3161"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "liver-images"

# 環境変数
[vars]
IMAGE_WORKER_URL = "https://liver-scraper-images.liver-scraper-detailsapi.workers.dev"

# シークレット環境変数（wrangler secret putで設定）
# LOGIN_EMAIL = "your-email@example.com"
# LOGIN_PASSWORD = "your-password"
