name = "liver-scraper-images"
main = "src/images-scraper.js"
compatibility_date = "2024-01-01"
account_id = "e610573ff233746b39a509deadc4ee36"

# Worker3: 画像収集専門 - 詳細完了の1-2時間後
[triggers]
crons = ["0 2,8,14,20 * * *"]

# 共有KVとR2バインディング
[[kv_namespaces]]
binding = "LIVER_DATA"
id = "a9658ebf09ed49bba4ea6b35af67f9eb"

[[kv_namespaces]]
binding = "IMAGE_HASHES"
id = "faaeff9c9c194751bc1e20549fdb3161"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "liver-images"

# シークレット環境変数（wrangler secret putで設定）
# LOGIN_EMAIL = "your-email@example.com"
# LOGIN_PASSWORD = "your-password"
