name = "liver-scraper-main"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "4cf5abc5b44aacd9b0776ac001d9826a"

[triggers]
crons = ["0 * * * *"]

[[kv_namespaces]]
binding = "LIVER_DATA"
id = "4adf452d17b14628a67d1bbe183d6b53"

[[kv_namespaces]]
binding = "IMAGE_HASHES"
id = "315e8927f3284e969d9657c0e97bbab8"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "liver-images"
